### ISSUE TITLE
tmdbsimple doesn't have a function for movie recommendations

### ISSUE THREAD

**Issue by wuhugh** [GatorWatch/GatorWatch#2]
[tmdbsimple](https://github.com/celiao/tmdbsimple) doesn't have a function to get the recommended movie lists, but it does have similar movies (they are two different things according to the official tmdb docs).

It does however have recommendations given a Tv show as well as similar Tv shows. Should we use recommendations for Tv and similar for movies or just use similar for both to keep consistency?

**Comment by TimMai** [comment]
We should probably provide similar movies and TV shows for consistency

**Comment by wuhugh** [comment]
Okay. I made a pull request. Now movies and Tv shows should have identical counterpart methods.
